FROM arm64v8/ubuntu:22.04

# install dependencies
RUN apt-get update && apt-get install -y \
    g++ \
    make \
    libeigen3-dev \
    git \
    scons \
    && rm -rf /var/lib/apt/lists/*

# copy code
COPY . /app
WORKDIR /app

# env
ENV LD_LIBRARY_PATH=/app/ComputeLibrary/build:$LD_LIBRARY_PATH

# build
# RUN make gemm
# RUN make sparse

# run
CMD ["./bin/gemm_bench"]